package SAA::Operations;

use strict;
require 5.002;
use vars qw(@EXPORT_OK);
# Only supported protocols are defined.
use vars qw(
	$PROTO_NA
	$PROTO_ICMP_ECHO
	$PROTO_UDP_ECHO
	$PROTO_SNA_RU_ECHO
	$PROTO_SNA_LU0_ECHO_APPL
	$PROTO_SNA_LU2_ECHO_APPL
	$PROTO_SNA_LU62_ECHO
	$PROTO_SNA_LU62_ECHO_APPL
	$PROTO_TCP_CONN
	$PROTO_HTTP_APPL
	$PROTO_DNS_APPL
	$PROTO_JITTER_APPL
	$PROTO_DLSW_APPL
	$PROTO_DHCP_APPL
	$PROTO_FTP_APPL
);
# XXX So we need a Type for each type of operation?
use vars qw(
    $TYPE_ECHO
	$TYPE_TCP_CONN
);

use vars qw(
    $MAX_THRESHOLD
	$MAX_FREQUENCY
	$MAX_TIMEOUT
);

@EXPORT_OK = qw(
	$PROTO_NA
	$PROTO_ICMP_ECHO
	$PROTO_UDP_ECHO
	$PROTO_SNA_RU_ECHO
	$PROTO_SNA_LU0_ECHO_APPL
	$PROTO_SNA_LU2_ECHO_APPL
	$PROTO_SNA_LU62_ECHO
	$PROTO_SNA_LU62_ECHO_APPL
	$PROTO_TCP_CONN
	$PROTO_HTTP_APPL
	$PROTO_DNS_APPL
	$PROTO_JITTER_APPL
	$PROTO_DLSW_APPL
	$PROTO_DHCP_APPL
	$PROTO_FTP_APPL
	$TYPE_ECHO
	$MAX_FREQUENCY
	$MAX_TIMEOUT
	$MAX_THRESHOLD
);

use Exporter();
use vars qw(@ISA);
@ISA = qw(Exporter);

$PROTO_NA = 1;
$PROTO_ICMP_ECHO = 2;
$PROTO_UDP_ECHO = 3;
$PROTO_SNA_RU_ECHO = 4;
$PROTO_SNA_LU0_ECHO_APPL = 5;
$PROTO_SNA_LU2_ECHO_APPL = 6;
$PROTO_SNA_LU62_ECHO = 7;
$PROTO_SNA_LU62_ECHO_APPL = 8;
$PROTO_TCP_CONN = 24;
$PROTO_HTTP_APPL = 25;
$PROTO_DNS_APPL = 26;
$PROTO_JITTER_APPL = 27;
$PROTO_DLSW_APPL = 28;
$PROTO_DHCP_APPL = 29;
$PROTO_FTP_APPL = 30;

$TYPE_ECHO = 1;

$MAX_FREQUENCY = 604800;
$MAX_TIMEOUT = 604800000;
$MAX_THRESHOLD = 2147483647;

